defmodule Euler.Two do
  @moduledoc """
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """
  def run(), do: two(1, 1, 0)

  def two(_, b, sum) when b >= 4_000_000, do: sum
  def two(a, b, sum) when rem(b, 2) == 0, do: two(b, a + b, sum + b)
  def two(a, b, sum), do: two(b, a + b, sum)
end
